# Create a new user
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="email"

user5@user.ru
--boundary
Content-Disposition: form-data; name="name"

Катя Петрова
--boundary
Content-Disposition: form-data; name="password"

123456
--boundary
Content-Disposition: form-data; name="sex"

Женский
--boundary
Content-Disposition: form-data; name="birthday"

1988-03-25
--boundary
Content-Disposition: form-data; name="location"

Петроградская
--boundary
Content-Disposition: form-data; name="role"

sportsman
--boundary
Content-Disposition: form-data; name="avatarFile"; filename="user-avatar.png"

< ../../../../uploads/default-photo/user-avatar.png
--boundary--

###

# Get user by ID
GET http://localhost:3000/api/users/679639cbad541ce71b1e37f3 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user4@user.ru",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk0N2ZjMzQ0NDRmYWM2MmE4MDVmYjgiLCJlbWFpbCI6IkFJQG5tYWlsLnJ1IiwibmFtZSI6IkFsZXhleSBJdmFub3YiLCJ0b2tlbklkIjoiZWYxN2U2ZGItY2MxYi00ZDBlLThiMzMtMzk2ODY0NTQ0NWViIiwiaWF0IjoxNzM3ODcwNjQ5LCJleHAiOjE3NDA0NjI2NDl9.lZMnHDaCqgmfWMzTn7RPE8_KMByJlNGJQW9ITyDuZPE
###

# Check user token
POST http://localhost:3000/api/users/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk0N2ZjMzQ0NDRmYWM2MmE4MDVmYjgiLCJlbWFpbCI6IkFJQG5tYWlsLnJ1IiwibmFtZSI6IkFsZXhleSBJdmFub3YiLCJpYXQiOjE3Mzc5OTI0NjIsImV4cCI6MTczNzk5Mjc2Mn0.oKhgOIWYMJF11rJ5P6BOfrIT-r31s4xjxgYz7oX_x8k

###

# Fill questionnaire
PUT http://localhost:3000/api/users/67d5a5cb391446eaf8b95805/questionnaire HTTP/1.1
Content-Type: application/json

{
  "specialization": [
    "running",
    "stretching"
  ],
  "Duration": "30-50 мин",
  "level": "Любитель",
  "caloriesLose": 3000,
  "caloriesWaste": 2000,
  "isReadyToTrain": true
}

###

# Get questionnaire
GET http://localhost:3000/api/users/67d5a5cb391446eaf8b95805 HTTP/1.1
Content-Type: application/json

###

# Update user
PATCH http://localhost:3000/api/users/update HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2Q3MzQyOTAwYjc4YmViM2I3ZWVjMDMiLCJlbWFpbCI6InVzZXI0QHVzZXIucnUiLCJuYW1lIjoi0JjQstCw0L0iLCJyb2xlIjoic3BvcnRzbWFuIiwiaWF0IjoxNzQyMTgxODU3LCJleHAiOjE3NDIxODI3NTd9.V4RI6Q9xG0AKBdIL5ST9KYAhREz5Fn0bS4x4gEhYYGY
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="description"

Я люблю сноуборд
--boundary
Content-Disposition: form-data; name="isReadyToTrain"

false
--boundary
Content-Disposition: form-data; name="specialization"

yoga
--boundary
Content-Disposition: form-data; name="specialization"

aerobics
--boundary
Content-Disposition: form-data; name="location"

Петроградская
--boundary
Content-Disposition: form-data; name="level"

Любитель
--boundary
Content-Disposition: form-data; name="avatarFile"; filename="user-avatar.png"

< ../../../../uploads/default-photo/user-avatar.png
--boundary--

###



