export const UserOperation = {
  Register: { summary: 'Регистрация нового пользователя' },
  Login: { summary: 'Авторизация пользователя' },
  GetUser: { summary: 'Получение информации о пользователе' },
  RefreshTokens: { summary: 'Обновление токенов' },
  Check: { summary: 'Проверка access токена' },
  FillUserQuestionnaire: { summary: 'Заполнение опросника пользователя' },
  FillCoachQuestionnaire: { summary: 'Заполнение опросника тренера' },
  GetQuestionnaire: { summary: 'Получение результатов опроса пользователя' },
  Update: { summary: 'Изменение данных о пользователе' },
  DeleteAvatar: { summary: 'Удаление аватара пользователя' },
  UpdateAvatar: { summary: 'Изменение аватара пользователя' },
  GetCertificates: { summary: 'Получение сертификатов и дипломов тренера' },
  AddCertificate: { summary: 'Добавление сертификата/диплома тренера' },
  UpdateCertificate: { summary: 'Изменение сертификата/диплома тренера' },
  DeleteCertificate: { summary: 'Удаление сертификата/диплома тренера' },
  ReadyToTrain: { summary: 'Получение списка пользователей, готовых к тренировки' },
} as const;
